target 'DWduifubao' do

pod 'Masonry'
pod 'SDCycleScrollView','~> 1.64'
pod 'LXMButtonImagePosition', '~> 1.1.1'
pod 'AFNetworking','~>3.1.0'
pod 'IQKeyboardManager'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengAnalytics'
pod 'TZImagePickerController' # 图片选择控制器

end

